# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
